version: '3.8'

services:
  backend:
    build:
      context: ./flask_server
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=spectrumK
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=database
    depends_on:
      - database

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    command: npm run start
    depends_on:
      - backend

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: spectrumK
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: